image: Ubuntu

stack: jdk 11

branches:
  only:
    - main

build: off

install:
  - docker-compose up -d
  - sleep 20
  - java -jar ./artifacts/aqa-shop.jar &
  - sleep 20
  - chmod +x gradlew

build_script:
  - ./gradlew test --info -Dselenide.headless=true
