version: '3.7'
services:
  postgres:
    image: mysql:8.0.18
    restart: always
    ports:
      - '8080:8080'
#    volumes:
#      - ./data:/var/lib/postgresql/data
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=app
      - MYSQL_USER=app
      - MYSQL_PASSWORD=pass